#!/usr/bin/env bash
# Regenerates manifest.js from the contents of ./images/.
# Run this whenever you add or remove image files:
#   ./generate-manifest.sh
#
# Browsers can't list a directory on their own (especially under file://),
# so the grid reads this generated list instead. The page layout stays pure CSS.

set -euo pipefail
cd "$(dirname "$0")"

{
  echo "// AUTO-GENERATED by generate-manifest.sh — do not edit by hand."
  echo "// Lists the image files in ./images/ that the grid renders as cards."
  echo "window.PROJECT_IMAGES = ["
  # Common web image types, case-insensitive, sorted, basename only.
  find images -maxdepth 1 -type f \
    \( -iname '*.svg' -o -iname '*.jpg' -o -iname '*.jpeg' \
       -o -iname '*.png' -o -iname '*.webp' -o -iname '*.gif' -o -iname '*.avif' \) \
    -exec basename {} \; \
    | LC_ALL=C sort \
    | sed 's/.*/  "&",/'
  echo "];"
} > manifest.js

count=$(grep -c '^  "' manifest.js || true)
echo "Wrote manifest.js with ${count} image(s)."
