#!/usr/bin/env bash
# Regenerates image-ratios.js from the pixel dimensions of the files in ./images/.
# Run this whenever you add or remove image files:
#   ./generate-ratios.sh
#
# The justified-rows gallery (justified-rows.js) needs each image's width/height
# ratio up front to break images into full-width rows without a load-time reflow.
# We read the dimensions with `sips` (ships with macOS, reads webp) so the layout
# is exact from the first paint. The pure-CSS pages don't use this.

set -euo pipefail
cd "$(dirname "$0")"

{
  echo "// AUTO-GENERATED by generate-ratios.sh — do not edit by hand."
  echo "// Maps each ./images/ file to its width/height aspect ratio, for the"
  echo "// justified-rows gallery (justified-rows.js)."
  echo "window.IMAGE_RATIOS = {"
  find images -maxdepth 1 -type f \
    \( -iname '*.svg' -o -iname '*.jpg' -o -iname '*.jpeg' \
       -o -iname '*.png' -o -iname '*.webp' -o -iname '*.gif' -o -iname '*.avif' \) \
    | LC_ALL=C sort \
    | while IFS= read -r f; do
        base=$(basename "$f")
        dims=$(sips -g pixelWidth -g pixelHeight "$f" 2>/dev/null \
          | awk '/pixelWidth/{w=$2} /pixelHeight/{h=$2} END{ if (h>0) printf "%.4f", w/h }')
        [ -n "$dims" ] && printf '  "%s": %s,\n' "$base" "$dims"
      done
  echo "};"
} > image-ratios.js

count=$(grep -c '":' image-ratios.js || true)
echo "Wrote image-ratios.js with ${count} ratio(s)."
