// AUTO-GENERATED by generate-manifest.sh — do not edit by hand.
// Lists the image files in ./images/ that the grid renders as cards.
window.PROJECT_IMAGES = [
  "atrium-residence.svg",
  "brick-workshop.svg",
  "canal-apartments.svg",
  "cliff-house.svg",
  "coastal-retreat.svg",
  "concrete-house.svg",
  "courtyard-villa.svg",
  "forest-chapel.svg",
  "gallery-extension.svg",
  "garden-pavilion.svg",
  "hillside-cabin.svg",
  "lakeside-sauna.svg",
  "market-hall.svg",
  "plaza-offices.svg",
  "riverside-pavilion.svg",
  "stone-cottage.svg",
  "terrace-housing.svg",
  "timber-studio.svg",
  "urban-infill.svg",
  "vault-library.svg",
];
