// Static project-list data for the demo. Mirrors the manifest.js pattern: a
// browser can't read the source spreadsheet under file://, so the rows live
// here as plain data. Fields: num, name, city (with country), category,
// status, year (a string, since some span a range e.g. "2021–2022").
window.PROJECTS = [
  { num: 606, name: "Rákosrendező Budapest Masterplan", city: "Budapest, HU", category: "masterplan", status: "competition (3rd prize)", year: "2026" },
  { num: 605, name: "Asllan Rusi Sport Palace Revitalisation", city: "Tirana, AL", category: "transformation", status: "competition", year: "2025" },
  { num: 604, name: "EXPO Real 2024", city: "Munich, DE", category: "pavilion", status: "completed", year: "2024" },
  { num: 603, name: "EXPO Albania", city: "Tirana, AL", category: "cultural", status: "competition", year: "2024" },
  { num: 602, name: "Haus der Jugend", city: "Vienna, AT", category: "mixed-use", status: "competition", year: "2023" },
  { num: 601, name: "Chalupkova Bratislava", city: "Bratislava, SK", category: "mixed-use", status: "competition", year: "2023" },
  { num: 600, name: "Blok 5.1", city: "Bratislava, SK", category: "residential", status: "competition (2nd prize)", year: "2024" },
  { num: 599, name: "EHQ", city: "Bratislava, SK", category: "residential", status: "competition (1st prize)", year: "2023" },
  { num: 598, name: "Lazne Vojtechov", city: "Vojtechov, CZ", category: "leisure", status: "competition", year: "2023" },
  { num: 597, name: "Hotel Cracovia", city: "Krakov, PL", category: "cultural", status: "competition", year: "2023" },
  { num: 596, name: "Americka", city: "Kladno, CZ", category: "residential", status: "competition", year: "2023" },
  { num: 595, name: "Pernink", city: "Pernink, CZ", category: "leisure", status: "study", year: "2023" },
  { num: 594, name: "Wiener Neustadt", city: "Vienna, AT", category: "residential", status: "competition", year: "2023" },
  { num: 593, name: "Smouli mesto", city: "Zlin, CZ", category: "mixed-use", status: "ongoing", year: "2023" },
  { num: 592, name: "Albanian football stadiums", city: "Tirana, AL", category: "leisure", status: "competition", year: "2023" },
  { num: 591, name: "ProWein", city: "Duesseldorf, GE", category: "pavilion", status: "completed", year: "2023" },
  { num: 590, name: "Primary School Mnichovo Hradiste", city: "Mnichovo Hradiste, CZ", category: "educational", status: "competition (2nd prize)", year: "2022" },
  { num: 589, name: "Vajnorska", city: "Bratislava, SK", category: "residential", status: "competition", year: "2022" },
  { num: 588, name: "Vinohradska", city: "Prague, CZ", category: "mixed-use", status: "competition", year: "2022" },
  { num: 587, name: "4. Quadrant", city: "Prague, CZ", category: "mixed-use", status: "competition", year: "2022" },
  { num: 586, name: "Southbank", city: "Bratislava, SK", category: "mixed-use", status: "competition", year: "2022" },
  { num: 585, name: "Prague Apartments", city: "Prague, CZ", category: "residential", status: "ongoing", year: "2022" },
  { num: 584, name: "Public space in front of the Church of the Holy Spirit", city: "Ostrava, CZ", category: "public space", status: "competition (3rd prize)", year: "2022" },
  { num: 583, name: "Brewery Znojmo", city: "Znojmo, CZ", category: "cultural", status: "ongoing", year: "2022" },
  { num: 582, name: "Viedenska street masterplan", city: "Bratislava, SK", category: "residential", status: "competition (2nd prize)", year: "2022" },
  { num: 581, name: "Yearbook", city: "CZ", category: "other", status: "completed", year: "2022" },
  { num: 580, name: "Hotel Straznice", city: "Straznice, CZ", category: "leisure", status: "ongoing", year: "2022" },
  { num: 579, name: "Czech Cities and Regions stand at Expo Real 2022", city: "Munich, DE", category: "pavilion", status: "completed", year: "2022" },
  { num: 578, name: "Villa in Hanspaulka", city: "Prague, CZ", category: "residential", status: "ongoing", year: "2022" },
  { num: 577, name: "Hrube Luky Residence", city: "Bratislava, SK", category: "residential", status: "competition", year: "2022" },
  { num: 576, name: "Paracentrum Lipova", city: "Brno, CZ", category: "other", status: "ongoing", year: "2021" },
  { num: 575, name: "Rohan Primary School", city: "Prague, CZ", category: "educational", status: "competition (3rd prize)", year: "2022" },
  { num: 574, name: "Kiosk in Zurich", city: "Zurich, CH", category: "other", status: "competition", year: "2022" },
  { num: 573, name: "Letna masterplan", city: "Kosice, SK", category: "masterplan", status: "competition (3rd prize)", year: "2022" },
  { num: 572, name: "Villa in Znojmo", city: "Znojmo, CZ", category: "residential", status: "ongoing", year: "2021" },
  { num: 571, name: "High speed railway terminal Roudnice", city: "Roudnice nad Labem, CZ", category: "infrastructure", status: "competition", year: "2021" },
  { num: 570, name: "Vydrica Water Tower", city: "Bratislava, SK", category: "cultural", status: "competition (3rd prize)", year: "2021" },
  { num: 569, name: "Academy of Performing Arts extension", city: "Bratislava, SK", category: "educational", status: "competition", year: "2021" },
  { num: 568, name: "Villa Nitra", city: "Nitra, SK", category: "residential", status: "ongoing", year: "2022" },
  { num: 567, name: "Valmez City architect", city: "Valasske Mezirici, CZ", category: "other", status: "ongoing", year: "2021" },
  { num: 566, name: "Healthy Longevity Cafe", city: "Prague, CZ", category: "leisure", status: "completed", year: "2021–2022" },
  { num: 565, name: "Nusle Brewery", city: "Prague, CZ", category: "residential", status: "ongoing", year: "2021" },
  { num: 564, name: "Multifunctional house", city: "Znojmo, CZ", category: "mixed-use", status: "ongoing", year: "2021" },
  { num: 563, name: "Forbes Jarabinky", city: "Bratislava, SK", category: "office", status: "ongoing", year: "2021" },
  { num: 562, name: "Usti masterplan", city: "Usti nad Labem, CZ", category: "masterplan", status: "study", year: "2021" },
  { num: 561, name: "Znojemska Park", city: "Pohorelice, CZ", category: "residential", status: "study", year: "2021" },
  { num: 560, name: "Sobes", city: "Podyji National Park, CZ", category: "leisure", status: "study", year: "2021" },
  { num: 559, name: "Smichov City", city: "Prague, CZ", category: "residential", status: "competition", year: "2021" },
  { num: 558, name: "Playful Interventions to Veszprem", city: "Veszprem, HU", category: "leisure", status: "ongoing", year: "2021" },
  { num: 557, name: "Komarovske embankment", city: "Brno, CZ", category: "mixed-use", status: "urban study", year: "2021" },
  { num: 556, name: "Louky District", city: "Ivancice, CZ", category: "masterplan", status: "ongoing", year: "2020" },
  { num: 555, name: "The European Film Center CAMERIMAGE", city: "Torun, PL", category: "cultural", status: "competition", year: "2021" },
  { num: 554, name: "CEK Skanska", city: "Prague, CZ", category: "residential", status: "competition", year: "2021" },
  { num: 553, name: "Villa in Hranice", city: "Hranice, CZ", category: "residential", status: "ongoing", year: "2021" },
  { num: 552, name: "Jablonecek", city: "Ralsko, CZ", category: "masterplan", status: "ongoing", year: "2021" },
  { num: 551, name: "Omice Quarry", city: "Omice, CZ", category: "residential", status: "ongoing", year: "2021" },
  { num: 550, name: "Husovka Housing", city: "Rosice, CZ", category: "masterplan", status: "ongoing", year: "2021" },
  { num: 549, name: "Tor Marancia Cultural Center", city: "Rome, IT", category: "cultural", status: "competition", year: "2021" },
  { num: 548, name: "Hradec neighborhood", city: "Hradec Kralove, CZ", category: "residential", status: "competition", year: "2021" },
  { num: 547, name: "KOMA Village", city: "Vizovice, CZ", category: "mixed-use", status: "ongoing", year: "2021" },
  { num: 546, name: "Stare Grunty Residence", city: "Bratislava, SK", category: "residential", status: "competition", year: "2020" },
  { num: 545, name: "Roofs&Roots", city: "Olomouc, CZ", category: "office", status: "study", year: "2020" },
  { num: 544, name: "Valmez Waterfront", city: "Valasske Mezirici, CZ", category: "public space", status: "ongoing", year: "2020" },
  { num: 543, name: "SZDC headquarters", city: "Prague, CZ", category: "office", status: "competition", year: "2020" },
  { num: 542, name: "Kralicak Masterplan", city: "Stare Mesto, CZ", category: "masterplan", status: "ongoing", year: "2020" },
  { num: 541, name: "Flexible Living", city: "Olomouc, CZ", category: "residential", status: "completed", year: "2023" },
  { num: 540, name: "Ride Parking", city: "Various", category: "infrastructure", status: "study", year: "2020" },
  { num: 539, name: "Depository for National Gallery Prague", city: "Prague, CZ", category: "cultural", status: "competition (2nd prize)", year: "2020" },
  { num: 538, name: "Rohan Island", city: "Prague, CZ", category: "masterplan", status: "competition", year: "2020" },
  { num: 537, name: "Senior house Hudečkova", city: "Prague, CZ", category: "residential", status: "competition", year: "2020" },
  { num: 536, name: "Mlynske nivy masterplan", city: "Bratislava, SK", category: "masterplan", status: "competition (3rd prize)", year: "2020" },
  { num: 535, name: "Opava Stadium Renovation", city: "Opava, CZ", category: "leisure", status: "competition", year: "2019" },
  { num: 534, name: "Bus station Vodnany", city: "Vodnany, CZ", category: "public space", status: "competition", year: "2019" },
  { num: 533, name: "HUBHUB Mlynske nivy", city: "Bratislava, SK", category: "office", status: "ongoing", year: "2019" },
  { num: 532, name: "Artcampus of Academy of Fine Arts and Design", city: "Bratislava, SK", category: "educational", status: "competition (2nd prize)", year: "2018–2019" },
  { num: 531, name: "Rohan Mixed Use District", city: "Prague, CZ", category: "mixed-use", status: "competition", year: "2019" },
  { num: 530, name: "Slovak pavilion at EXPO 2020", city: "Dubai, UAE", category: "cultural", status: "competition", year: "2018" },
  { num: 529, name: "Cejl 76 reuse", city: "Brno, CZ", category: "masterplan", status: "competition (1st prize)", year: "2018" },
  { num: 528, name: "Slezanka reconstruction", city: "Opava, CZ", category: "public space", status: "ongoing", year: "2018" },
  { num: 527, name: "U Milosrdnych apartments", city: "Prague, CZ", category: "residential", status: "competition", year: "2018" },
  { num: 526, name: "BVV Pavilon C+D", city: "Brno, CZ", category: "public space", status: "competition (2nd prize)", year: "2018" },
  { num: 525, name: "Metro station Krizikova", city: "Prague, CZ", category: "public space", status: "study", year: "2018" },
  { num: 524, name: "Balcarkova apartments", city: "Olomouc, CZ", category: "masterplan", status: "ongoing", year: "2018" },
  { num: 523, name: "New Zbrojovka", city: "Brno, CZ", category: "masterplan", status: "competition", year: "2018" },
  { num: 522, name: "Paracentrum Fenix", city: "Brno, CZ", category: "public space", status: "ongoing", year: "2018" },
  { num: 521, name: "Slovenka 2.0", city: "Banska Bystrica, SK", category: "masterplan", status: "ongoing", year: "2018" },
  { num: 520, name: "Pod Juliskou apartments", city: "Prague, CZ", category: "masterplan", status: "competition", year: "2017" },
  { num: 519, name: "Innovatrics Headquarters", city: "Bratislava, SK", category: "office", status: "competition (3rd prize)", year: "2017" },
  { num: 518, name: "Modernization of the Surgical Centre of the Faculty Hospital", city: "Hradec Kralove, CZ", category: "public space", status: "competition (3rd prize)", year: "2017" },
  { num: 517, name: "Urban infill Strakonicka 72", city: "Prague, CZ", category: "mixed-use", status: "competition", year: "2017" },
  { num: 516, name: "Tovarenska", city: "Bratislava, SK", category: "residential", status: "competition", year: "2017" },
  { num: 515, name: "Kopcianska", city: "Bratislava, SK", category: "masterplan", status: "competition", year: "2017" },
  { num: 514, name: "Forbes Slovakia", city: "Bratislava, SK", category: "office", status: "completed", year: "2017" },
  { num: 513, name: "Lofts Kominarska", city: "Bratislava, SK", category: "residential", status: "competition", year: "2017" },
  { num: 512, name: "Chapel in Antarctica", city: "James Ross Island, Antarctica", category: "public space", status: "study", year: "2016" },
  { num: 511, name: "Cvernovka 2.0", city: "Bratislava, SK", category: "masterplan", status: "competition", year: "2016" },
  { num: 510, name: "Gallery of Trash", city: "Hranice, CZ", category: "public space", status: "study", year: "2016" },
  { num: 509, name: "2 Villas on Cerveny kopec", city: "Brno, CZ", category: "residential", status: "ongoing", year: "2016" },
  { num: 508, name: "New cityhall of Prague 7", city: "Prague, CZ", category: "public space", status: "competition", year: "2016" },
  { num: 507, name: "Moravian Gallery", city: "Brno, CZ", category: "cultural", status: "completed", year: "2022–2024" },
];
